redis:
  replicaCount: 2
  image:
    repository: redis
    tag: alpine

microservice:
  services:
    - name: emailservice
      image: gcr.io/google-samples/microservices-demo/emailservice:v0.8.0
      port: 8080
      replicaCount: 2

    - name: recommendationservice
      image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.8.0
      port: 8080
      replicaCount: 2

    - name: productcatalogservice
      image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0
      port: 3550
      replicaCount: 2

    - name: paymentservice
      image: gcr.io/google-samples/microservices-demo/paymentservice:v0.8.0
      port: 50051
      replicaCount: 2

    - name: currencyservice
      image: gcr.io/google-samples/microservices-demo/currencyservice:v0.8.0
      port: 7000
      replicaCount: 2

    - name: shippingservice
      image: gcr.io/google-samples/microservices-demo/shippingservice:v0.8.0
      port: 50051
      replicaCount: 2

    - name: adservice
      image: gcr.io/google-samples/microservices-demo/adservice:v0.8.0
      port: 9555
      replicaCount: 2

    - name: cartservice
      image: gcr.io/google-samples/microservices-demo/cartservice:v0.8.0
      port: 7070
      replicaCount: 2

    - name: checkoutservice
      image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.8.0
      port: 5050
      replicaCount: 2

    - name: frontend
      image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
      port: 8080
      replicaCount: 2

