apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-umbrella
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aaleem123/GKE-Helm-Argocd-Microservices.git
    targetRevision: HEAD
    path: charts/umbrella-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

