{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        ports:
          - containerPort: {{ .port }}
{{- if .env }}
        env:
{{- range .env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
{{- end }}
{{- end }}
{{- end }}

