{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .serviceType | default "ClusterIP" }}
  selector:
    app: {{ .name }}
  ports:
  - protocol: TCP
    port: {{ .port }}
    targetPort: {{ .port }}
{{- end }}
